services:
    js:
        image: sombrepigeon/releases:js
        build:
            context: .
            args:
                EXT: js
            dockerfile: Containerfile #compatibility :/
    css:
        image: sombrepigeon/releases:css
        build:
            context: .
            args:
                EXT: css
            dockerfile: Containerfile #compatibility :/
    js-dev:
        image: sombrepigeon/releases:js-dev
        build:
            context: .
            args:
                EXT: js
            dockerfile: Containerfile #compatibility :/
    css-dev:
        image: sombrepigeon/releases:css-dev
        build:
            context: .
            args:
                EXT: css
            dockerfile: Containerfile #compatibility :/


